<a href="https://colab.research.google.com/github/sshekc3/demo/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
gemini_api_key="AIzaSyDrru4TgSbQzKKvuhWYiSHk5K0LtmVBGDk"
news_api_key="c9a69a190a8c445e82d99ce1f3309ec7"

In [61]:
!pip install -q -U google-genai
!pip install newsapi-python
!pip install sentence-transformers
!pip install lxml_html_clean
!pip install newspaper3k
!pip install -q -U google-genai
!pip install streamlit

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: newsapi-python in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (0.2.7)
Requirement already satisfied: requests<3.0.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newsapi-python) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3.0.0->newsapi-python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3.0.0->newsapi-python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3.0.0->newsapi-python) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3.0.0->newsapi-python) (2026.2.25)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: sentence-transformers in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (5.6.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (1.12.0)
Requirement already satisfied: torch>=1.11.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (2.4.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: lxml_html_clean in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (0.4.4)
Requirement already satisfied: lxml in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from lxml_html_clean) (6.1.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: newspaper3k in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (0.2.8)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (4.14.3)
Requirement already satisfied: Pillow>=3.3.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (12.1.1)
Requirement already satisfied: PyYAML>=3.11 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: cssselect>=0.9.2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (1.4.0)
Requirement already satisfied: lxml>=3.6.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (6.1.0)
Requirement already satisfied: nltk>=3.2.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (3.9.4)
Requirement already satisfied: requests>=2.10.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (2.32.5)
Requirement already satisfied: feedparser>=5.2.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (5.3.1)
Requirement already satisfied: feedfinder2>=0.0.4 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from nltk>=3.2.1->newspaper3k) (8.3.1)
Requirement already satisfied: joblib in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from nltk>=3.2.1->newspaper3k) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from nltk>=3.2.1->newspaper3k) (2026.4.4)
Requirement already satisfied: tqdm in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from nltk>=3.2.1->newspaper3k) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests>=2.10.0->newspaper3k) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests>=2.10.0->newspaper3k) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests>=2.10.0->newspaper3k) (2026.2.25)
Requirement already satisfied: requests-file>=1.4 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from tldextract>=2.0.1->newspaper3k) (3.29.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.1.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.0.6-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: click<9,>=7.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (8.3.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.47-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.23 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (2.4.2)
Requirement already satisfied: packaging>=20 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (3.0.1)
Requirement already satisfied: pillow<13,>=7.1.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (12.1.1)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (6.33.6)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (3.0 kB)
Requirement already satisfied: requests<3,>=2.27 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (9.1.4)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (6.5.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from streamlit) (4.15.0)
Requirement already satisfied: jinja2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=2.4.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.20.0-py3-none-any.whl.metadata (15 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached rpds_py-0.30.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: six>=1.5 in /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 293.1 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading altair-6.1.0-py3-none-any.whl (796 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.0/797.0 kB 799.7 kB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-7.0.6-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.47-py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 kB 758.3 kB/s eta 0:00:00 kB/s eta 0:00:01:01
Downloading pyarrow-24.0.0-cp311-cp311-macosx_12_0_arm64.whl (35.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 701.2 kB/s eta 0:00:00m eta 0:00:01[36m0:00:02
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 676.9 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 735.7 kB/s eta 0:00:00 kB/s eta 0:00:01
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading narwhals-2.20.0-py3-none-any.whl (449 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.4/449.4 kB 830.0 kB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)

In [62]:
from google import genai
from newsapi import NewsApiClient
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from newspaper import Article
import streamlit as st

In [53]:
llm_client = genai.Client(api_key=gemini_api_key)
newsapi_client = NewsApiClient(api_key=news_api_key)
model = SentenceTransformer('all-MiniLM-L6-v2')

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8684.73it/s]

In [54]:
import json
from pathlib import Path
from google.genai import types


def get_prompt(file_path: str):
    base_dir =  Path.cwd()
    template_path = base_dir / "prompts" / file_path
    template = Path(template_path).read_text()
    return template
def generate_ans(data: str, prompt_path: str):
    prompt = get_prompt(prompt_path)

    input_text = f"""
    {prompt}
    ##input
    {data}
    """

    response = llm_client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=input_text,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",  # 🔥 IMPORTANT
        ),
    )
    return response.text

In [33]:
def fetch_article(url):
    try:
        article = Article(url)
        article.download()
        article.parse()
        
        return article.text
    except Exception as e:
        return None

In [56]:
def compute_total_score(row):
    deal_weight_map = {
        "acquisition": 10,
        "merger": 9,
        "investment": 8,
        "partnership": 6,
        "none": 0
    }

    deal_weight = deal_weight_map.get(row['deal_type'], 0)

    entities = row['fmcg_entities']
    entity_score = min(len(entities) * 2, 10) if isinstance(entities, list) else 0

    total_score = (
        0.5 * row['relevance_score'] +
        0.2 * (row['confidence_score'] * 10) +
        0.2 * deal_weight +
        0.1 * entity_score
    )

    return round(total_score, 2)

In [34]:
EXPECTED_KEYS = {
    "is_relevant": False,
    "relevance_score": 0,
    "confidence_score": 0.0,
    "deal_type": "none",
    "fmcg_entities": [],
    "keywords": [],
    "summary": "",
    "reason": ""
}
def parse_and_fill(response_text):
    try:
        data = json.loads(response_text)
    except:
        data = {}

    for key, default in EXPECTED_KEYS.items():
        if key not in data or data[key] is None:
            data[key] = default

    return data

In [35]:
def score_article(full_text:str):
    response =generate_ans(data=full_text,prompt_path='score_system.md')
    return parse_and_fill(response)

In [39]:
# Get headlines
response = newsapi_client.get_everything(
    q='(FMCG OR "consumer goods" OR retail) AND (acquisition OR merger OR deal OR partnership OR investment)',
    page_size=10

)
df = pd.DataFrame(response['articles'])
df

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f..."
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...

In [46]:

# convert to embeddings and add it to dataframe
df['description'] = df['description'].fillna('')

embeddings = model.encode(df['description'].tolist(), convert_to_tensor=True)
df['description_embedding'] = embeddings.cpu().numpy().tolist()
df

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 0, '..."
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': False, 'relevance_score': 0, '..."
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",,"{'is_relevant': False, 'relevance_score': 0, '..."
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': False, 'relevance_score': 0, '..."
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '..."
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c..."
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 9, 'c..."

In [64]:
# remove similar articles
similarity_matrix = util.cos_sim(embeddings, embeddings)

threshold = 0.8
to_remove = set()

for i in range(len(df)):
    if i in to_remove:
        continue
        
    for j in range(i + 1, len(df)):
        if similarity_matrix[i][j] > threshold:
            to_remove.add(j)

df= df.drop(index=list(to_remove)).reset_index(drop=True)
df

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 2, '..."
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': True, 'relevance_score': 5, 'c..."
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",,"{'is_relevant': False, 'relevance_score': 0, '..."
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': True, 'relevance_score': 8, 'c..."
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '..."
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c..."
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 6, 'c..."

In [48]:
df['full_text'] = df['url'].apply(fetch_article)
df

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 0, '..."
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': False, 'relevance_score': 0, '..."
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",NaN,"{'is_relevant': False, 'relevance_score': 0, '..."
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': False, 'relevance_score': 0, '..."
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '..."
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c..."
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 9, 'c..."

In [55]:
df['full_text'] = df['full_text'].fillna('')
df['parsed'] = df['full_text'].apply(score_article)
parsed_df = pd.json_normalize(df['parsed'])
df_final = pd.concat([df, parsed_df], axis=1)
df_final

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed,is_relevant,relevance_score,confidence_score,deal_type,fmcg_entities,keywords,summary,reason
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 2, '...",False,2,1.00,none,[Medicube],"[skincare, coupon code, discount, rewards prog...",This article is a consumer-focused review and ...,The content is purely marketing and promotiona...
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': True, 'relevance_score': 5, 'c...",True,5,0.85,merger,"[Hugo Boss, Lego]","[Khaby Lame, Rich Sparkle Holdings, merger, e-...",TikTok influencer Khaby Lame's $975 million me...,The news describes a merger deal intended to f...
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],[],No content was provided for analysis.,"The input fields (title, description, and cont..."
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': True, 'relevance_score': 8, 'c...",True,8,1.00,acquisition,"[Walmart, Vizio]","[acquisition, retail, advertising, streaming, ...",Walmart is implementing mandatory account logi...,The article discusses the post-merger integrat...
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],"[private credit, redemption requests, asset ma...",The article discusses the shift in the private...,The article is entirely focused on the financi...
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c...",True,9,1.00,acquisition,"[Pepper, Alima]","[acquisition, food distribution, B2B food supp...",New York-based technology platform Pepper has ...,This news covers a direct acquisition within t...
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 6, 'c...",True,6,0.95,partnership,"[Amazon, Walmart, Whole Foods]","[Project Kobe, supercenter, grocery, automated...","Amazon is developing 'Project Kobe,' a new lar...",The article details a significant strategic in...

In [ ]:
df_final['total_score'] = df_final.apply(compute_total_score, axis=1)
df_final

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed,is_relevant,relevance_score,confidence_score,deal_type,fmcg_entities,keywords,summary,reason,total_score
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 2, '...",False,2,1.00,none,[Medicube],"[skincare, coupon code, discount, rewards prog...",This article is a consumer-focused review and ...,The content is purely marketing and promotiona...,3.2
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': True, 'relevance_score': 5, 'c...",True,5,0.85,merger,"[Hugo Boss, Lego]","[Khaby Lame, Rich Sparkle Holdings, merger, e-...",TikTok influencer Khaby Lame's $975 million me...,The news describes a merger deal intended to f...,6.4
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],[],No content was provided for analysis.,"The input fields (title, description, and cont...",2.0
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': True, 'relevance_score': 8, 'c...",True,8,1.00,acquisition,"[Walmart, Vizio]","[acquisition, retail, advertising, streaming, ...",Walmart is implementing mandatory account logi...,The article discusses the post-merger integrat...,8.4
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],"[private credit, redemption requests, asset ma...",The article discusses the shift in the private...,The article is entirely focused on the financi...,2.0
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c...",True,9,1.00,acquisition,"[Pepper, Alima]","[acquisition, food distribution, B2B food supp...",New York-based technology platform Pepper has ...,This news covers a direct acquisition within t...,8.9
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 6, 'c...",True,6,0.95,partnership,"[Amazon, Walmart, Whole Foods]","[Project Kobe, supercenter, grocery, automated...","Amazon is developing 'Project Kobe,' a new lar...",The article details a significant strategic in...,6.7

In [60]:
df_sorted = df_final.sort_values(by='total_score', ascending=False)
df_sorted

,source,author,title,description,url,urlToImage,publishedAt,content,description_embedding,full_text,parsed,is_relevant,relevance_score,confidence_score,deal_type,fmcg_entities,keywords,summary,reason,total_score
5,"{'id': 'the-next-web', 'name': 'The Next Web'}",Ana Maria Constantin,Pepper acquires YC-backed Alima to bring AI to...,"Pepper, a New York-based technology platform f...",https://thenextweb.com/news/pepper-acquires-al...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2026-03-25T17:01:48Z,"Pepper, a New York-based technology platform f...","[-0.05566294118762016, -0.045111097395420074, ...","Pepper, a New York-based technology platform f...","{'is_relevant': True, 'relevance_score': 9, 'c...",True,9,1.00,acquisition,"[Pepper, Alima]","[acquisition, food distribution, B2B food supp...",New York-based technology platform Pepper has ...,This news covers a direct acquisition within t...,8.9
3,"{'id': None, 'name': 'CNET'}",Ty Pendlebury,"New Vizio TVs Will Require Walmart Accounts, R...",The retail giant bought TV manufacturer Vizio ...,https://www.cnet.com/tech/home-entertainment/n...,https://www.cnet.com/a/img/resize/398a9a446e01...,2026-03-27T21:19:25Z,Customers who buy a new Vizio TV may need to s...,"[0.019333966076374054, -0.01046509575098753, 0...",Customers who buy a new Vizio TV may need to s...,"{'is_relevant': True, 'relevance_score': 8, 'c...",True,8,1.00,acquisition,"[Walmart, Vizio]","[acquisition, retail, advertising, streaming, ...",Walmart is implementing mandatory account logi...,The article discusses the post-merger integrat...,8.4
6,"{'id': 'business-insider', 'name': 'Business I...",Eugene Kim,Inside Project Kobe: Amazon's plan to build Wa...,Amazon's Project Kobe aims to disrupt Walmart ...,https://www.businessinsider.com/amazon-buildin...,https://i.insider.com/69c59dc44133f63e1c778c82...,2026-03-27T09:00:01Z,An Amazon employee picks up grocery productsMo...,"[-0.058442238718271255, -0.025445977225899696,...",Amazon is moving deeper into Walmart's territo...,"{'is_relevant': True, 'relevance_score': 6, 'c...",True,6,0.95,partnership,"[Amazon, Walmart, Whole Foods]","[Project Kobe, supercenter, grocery, automated...","Amazon is developing 'Project Kobe,' a new lar...",The article details a significant strategic in...,6.7
1,"{'id': 'business-insider', 'name': 'Business I...","Lucia Moses,Dan Whateley",Khaby Lame's mystery: TikTok's top creator tea...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,https://i.insider.com/69d55640f36fd1a78c0519d4...,2026-04-09T09:05:01Z,TikToker Khaby Lame's $975 announced deal has ...,"[0.03192226588726044, 0.007165881805121899, 0....",Khaby Lame's mysterious $975 million deal has ...,"{'is_relevant': True, 'relevance_score': 5, 'c...",True,5,0.85,merger,"[Hugo Boss, Lego]","[Khaby Lame, Rich Sparkle Holdings, merger, e-...",TikTok influencer Khaby Lame's $975 million me...,The news describes a merger deal intended to f...,6.4
0,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,Medicube Coupon Code: Top Promo Codes and Disc...,Use a Medicube coupon code to save on k-beauty...,https://www.wired.com/story/medicube-coupon-code/,https://media.wired.com/photos/67b63b985a505b0...,2026-04-09T05:00:00Z,Medicube is a Korean skincare brand known for ...,"[-0.060251157730817795, 0.01621752604842186, -...",Medicube is a Korean skincare brand known for ...,"{'is_relevant': False, 'relevance_score': 2, '...",False,2,1.00,none,[Medicube],"[skincare, coupon code, discount, rewards prog...",This article is a consumer-focused review and ...,The content is purely marketing and promotiona...,3.2
2,"{'id': None, 'name': 'TheStreet'}",Fernanda Tronco,36-year-old retailer shuts down website as all...,Long-established retail brands were once viewe...,https://www.thestreet.com/retail/36-year-old-r...,https://s.yimg.com/os/en/thestreet_881/a2021d2...,2026-04-15T21:47:00Z,Long-established retail brands were once viewe...,"[0.03738236799836159, -0.015038945712149143, -...",,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],[],No content was provided for analysis.,"The input fields (title, description, and cont...",2.0
4,"{'id': 'business-insider', 'name': 'Business I...",Alex Nicoll,One of the most stressful jobs in finance righ...,The retail boom in private credit has brought ...,https://www.businessinsider.com/private-credit...,https://i.insider.com/69e2aecea98bc8fdc096c0e7...,2026-04-20T09:11:02Z,AnVr/Getty Images\r\n<ul><li>Private credit's ...,"[0.019172677770256996, -0.08401276916265488, 0...",The private credit boom created a lucrative jo...,"{'is_relevant': False, 'relevance_score': 0, '...",False,0,1.00,none,[],"[private credit, redemption requests, asset ma...",The article discusses the shift in the private...,The article is entirely focused on the financi...,2.0

In [63]:

st.title("FMCG Deal Intelligence 📩")

# Email input
email = st.text_input("Enter your email:")

# Optional: text input (article or trigger)
user_input = st.text_area("Enter article text (optional):")

# Button
if st.button("Send Analysis"):
    if not email or "@" not in email:
        st.error("Please enter a valid email")
    else:
        with st.spinner("Processing..."):
            # call your pipeline
            if user_input.strip():
                result = score_article(user_input)
            else:
                result = {"message": "No input provided, but pipeline can run here"}

            # simulate sending email
            st.success(f"Analysis sent to {email}")

            # show result in UI also
            st.json(result)

2026-04-26 12:42:37.238 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.285
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/pratikshekhar/.pyenv/versions/3.11.8/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]
2026-04-26 12:42:37.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.287 Session state does not function when running a script without `streamlit run`
2026-04-26 12:42:37.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-26 12:42:37.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
import os
os.environ["OPENAI_API_KEY"] = "sk-...bZMA"

In [ ]:
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")

In [ ]:
from openai import OpenAI
import os

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [ ]:
def summarize(text):
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": f"Summarize this FMCG deal news in 2 lines:\n{text}"
                }
            ]
        )
        return response.choices[0].message.content
    except:
        return text[:200]  # fallback

In [ ]:
def run_pipeline():
    data = fetch_news()

    df = clean_data(data)
    df = deduplicate(df)
    df = apply_scoring(df)

    df.to_csv("fmcg_news.csv", index=False)

    generate_newsletter(df)

    return df

In [ ]:
import streamlit as st

st.title("FMCG Deal Intelligence Agent")

email = st.text_input("Enter your email")

if st.button("Generate & Send Newsletter"):
    df = run_pipeline()

    st.success("Newsletter generated!")

    st.dataframe(df[["title", "score"]])

    # download buttons
    st.download_button("Download CSV", open("fmcg_news.csv", "rb"), "data.csv")
    st.download_button("Download Word", open("newsletter.docx", "rb"), "newsletter.docx")

    if email:
        send_email(email)
        st.success("Email sent successfully!")

2026-04-25 05:19:12.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:12.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-25 05:19:13.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
import smtplib
from email.message import EmailMessage
import os

EMAIL = os.getenv("EMAIL_USER")
PASSWORD = os.getenv("EMAIL_PASS")

def send_email(to_email):
    msg = EmailMessage()
    msg["Subject"] = "FMCG Newsletter"
    msg["From"] = EMAIL
    msg["To"] = to_email

    msg.set_content("Attached is your FMCG newsletter")

    with open("newsletter.docx", "rb") as f:
        msg.add_attachment(f.read(), maintype="application", subtype="octet-stream", filename="newsletter.docx")

    with open("fmcg_news.csv", "rb") as f:
        msg.add_attachment(f.read(), maintype="application", subtype="octet-stream", filename="data.csv")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(EMAIL, PASSWORD)
        smtp.send_message(msg)

### Setting Environment Variables

YouYou can set environment variables directly within a Python cell using `os.environ`. This will make them available for the current Colab session. For example:

In [ ]:
import os

os.environ["EMAIL_USER"] = "your_actual_email@gmail.com" # Replace with your email
os.environ["EMAIL_PASS"] = "your_email_app_password" # Replace with your app password

print("Environment variables EMAIL_USER and EMAIL_PASS set.")

Environment variables EMAIL_USER and EMAIL_PASS set.

Alternatively, you can use the `env` magic command in a code cell, but this is generally less common for setting credentials that need to be accessed by `os.getenv()` in Python functions.

```python
%env EMAIL_USER=your_actual_email@gmail.com
%env EMAIL_PASS=your_email_app_password
```

**Important Security Note:** Directly setting credentials like this in your notebook makes them visible to anyone who views the notebook. For production environments or sharing, always prefer using Colab's built-in Secrets manager, as described in the markdown cell 'Using Secrets for Email Credentials' (`85fb4a7f`) and implemented in the `send_email_from_secrets` function (`8ccdfa42`).

In [ ]:
import subprocess

subprocess.run(['python', 'scheduler.py'])

CompletedProcess(args=['python', 'scheduler.py'], returncode=2)

In [ ]:
!streamlit run app.py

Usage: streamlit run [OPTIONS] [TARGET] [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py

In [ ]:
%%writefile app.py
import streamlit as st

st.title("FMCG Deal Intelligence Agent")

email = st.text_input("Enter your email")

if st.button("Generate & Send Newsletter"):
    df = run_pipeline()

    st.success("Newsletter generated!")

    st.dataframe(df[["title", "score"]])

    # download buttons
    st.download_button("Download CSV", open("fmcg_news.csv", "rb"), "data.csv")
    st.download_button("Download Word", open("newsletter.docx", "rb"), "newsletter.docx")

    if email:
        send_email(email)
        st.success("Email sent successfully!")

Writing app.py